#ifndef CONFIG_H
#define CONFIG_H

#define FIRST_JSON_OBJECT_SIZE 50 /* adjustable, arbitrary size */
#define SPARE_OBJECT_OR_ARRAY_MEMBERS_SIZE FIRST_JSON_OBJECT_SIZE * 10 /* adjustable, arbitrary size */
#define SPARE_CHARS_SIZE 5000 /* adjustable, arbitrary size up to UMAX_LONG */
#define MAX_WHITESPACE_AROUND_STRUCTURAL_CHARACTER 100

#define NODE_IP_ADDRESS_SIZE 39
#define PORT_SIZE 5
#define HTTP_RESPONSE_SIZE 1000000

enum exit_codes {SUCCESS, EXIT, NO, YES,EXIT_PROGRAM, EOF_SEEN, CONTINUE, FAILURE, TRUE, FALSE, UNFINISHED_MESSAGE, FINISHED_MESSAGE,CONNECTION_CLOSED,NO_MESSAGE};

#endif
